### ISSUE TITLE
Fresh install doesn't start

### ISSUE THREAD

**Issue by Cogitri** [flathub/org.kde.kiten#1]
Hello,

after installing Kiten on Fedora Silverblue with Flatpak the following error occurs and the application doesn't start:

```sh
$ flatpak run org.kde.kiten
ASSERT failure in KCatalogPrivate::setupGettextEnv: "You need to instantiate a Q*Application before using KCatalog", file src/kcatalog.cpp, line 223
```

**Comment by cho2** [comment]
> `ASSERT failure in KCatalogPrivate::setupGettextEnv: "You need to instantiate a Q*Application before using KCatalog", file src/kcatalog.cpp, line 223`

Similar to https://github.com/flathub/org.kde.digikam/issues/13.

**Comment by tsdgeos** [comment]
As i mentioned in the review this is fixed by https://invent.kde.org/education/kiten/-/commit/2fdfdb6f20525dd3f9d679dad7d86261cf885cff but i guess it got drowned in the comments in the review.

@cho2 If you have time you can prepare a patch now or wait a few days and it'll be in 20.08.3

**Comment by cho2** [comment]
https://github.com/flathub/org.kde.kiten/pull/2

It works on Silverblue 33

![Cuplikan layar dari 2020-10-30 14-42-36](https://user-images.githubusercontent.com/6271071/97673365-42196100-1abe-11eb-8166-cc438ab8ab28.png)

**Comment by cho2** [comment]
Merged https://github.com/flathub/org.kde.kiten/pull/2

**Comment by Cogitri** [comment]
Yup, works now, thanks for looking into it!
